---
- name: Install Java 11
  hosts: solid_servers
  become: yes

  tasks:
    - name: Check if Java 11 is installed
      command: java -version
      register: java_11_version_output
      ignore_errors: yes

    - name: Install Java 11
      yum:
        name: java-11-openjdk.x86_64
        state: present
      when: "'11' not in java_11_version_output.stderr"
