- name: Run Searcher App
  hosts: solid_servers
  become: yes

  vars:
    Search_Project_Path: "/usr/local/demos/ESPRESSO/Searcher"
    MetaIndex: "health2metaindex.csv"

  tasks:
    - name: Run server.js script
      become: true
      shell: "node  {{ Search_Project_Path }}/espresso_rdf_searcher.js {{ ansible_host }} {{MetaIndex}}"
      async: 3600
      poll: 0
      register: script_task

    - name: Wait for script to finish
      become: true
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 8081
        state: started
      when: script_task is defined and script_task.finished

    - name: Print script status
      debug:
        msg: "server.js script is running on {{ inventory_hostname }} with PID {{ script_task.ansible_pid }}"
      when: script_task is defined and script_task.finished and script_task.status == 'SUCCESS'
