- name: Run Searcher App
  hosts: solid_servers
  become: yes

  vars:
    Search_Project_Path: "/usr/local/ESPRESSO/Searcher/NewSearch_HTTPGet_Keyword_New"


  tasks:

    - name: Set MetaIndex Variable
      set_fact:
        MetaIndex: "{{ 'wwwj0partexprametaindex.csv' if (inventory_hostname_short | regex_replace('cups', '') | int) <= 10 else 'wwwj1partexprametaindex.csv' if (inventory_hostname_short | regex_replace('cups', '') | int) <= 20 else 'wwwj2partexprametaindex.csv' if (inventory_hostname_short | regex_replace('cups', '') | int) <= 30 else 'wwwj3partexprametaindex.csv' if (inventory_hostname_short | regex_replace('cups', '') | int) <= 40 else 'wwwj4partexprametaindex.csv' }}"

    - name: Run server.js script
      become: true
      shell: "node  {{ Search_Project_Path }}/index_MergeSort_Optmized_V2.js {{ ansible_host }} {{MetaIndex}}"
      async: 3600
      poll: 0
      register: script_task

    - name: Wait for script to finish
      become: true
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 8080
        state: started
      when: script_task is defined and script_task.finished

    - name: Print script status
      debug:
        msg: "server.js script is running on {{ inventory_hostname }} with PID {{ script_task.ansible_pid }}"
      when: script_task is defined and script_task.finished and script_task.status == 'SUCCESS'
