---
- name: Unzip files on remote VMs
  hosts: solid_servers
  become: yes

  tasks:
    - name: Unzip Data Files
      unarchive:
        src: "/srv/espresso/ardfhealthpod1{{ item }}.zip"
        dest: "/srv/espresso/storage/ardfhealthpod1{{ item }}/"
        remote_src: yes
      with_sequence: start=0 end=9499

    - name: Unzip Indexing Files
      unarchive:
        src: "/srv/espresso/ardfhealthpod1{{ item }}.index.zip"
        dest: "/srv/espresso/storage/ardfhealthpod1{{ item }}/espressoindex/"
        remote_src: yes
      with_sequence: start=0 end=9499
