---
- name: Unzip files on remote VMs
  hosts: solid_servers
  become: yes

  tasks:
    - name: Unzip Data Files
      unarchive:
        src: "/srv/espresso/E1exp{{ item }}.zip"
        dest: "/srv/espresso/storage/E1exp{{ item }}/"
        remote_src: yes
      with_sequence: start=0 end=49

    - name: Unzip Indexing Files
      unarchive:
        src: "/srv/espresso/E1exp{{ item }}.index.zip"
        dest: "/srv/espresso/storage/E1exp{{ item }}/espressoindex/"
        remote_src: yes
      with_sequence: start=0 end=49
